var markers = [
	  {latLng: [48.69, 2.09], name: 'Paris', weburl : "http://www.recontact.me"},
	  {latLng: [-22.65, -43.67], name: 'Rio de Janeiro', weburl : "http://www.recontact.me"},
	  {latLng: [-23.85, -46.89], name: 'São Paulo', weburl : "http://www.recontact.me"},
	  {latLng: [-25.47, -54.60], name: 'Iguazu Falls', weburl : "http://www.recontact.me"},
	  {latLng: [-27.20, -55.89], name: 'Trinidad', weburl : "http://www.recontact.me"},
	  {latLng: [-25.26, -57.67], name: 'Asunción', weburl : "http://www.recontact.me"},
	  {latLng: [-28.10, -57.62], name: 'Esteros del Iberá', weburl : "http://www.recontact.me"},
	  {latLng: [-27.20, -58.96], name: 'Resistencia', weburl : "http://www.recontact.me"},
	  {latLng: [-24.26, -65.40], name: 'Salta', weburl : "http://www.recontact.me/merci.php"},
	  {latLng: [-20.63, -66.75], name: 'Uyuni', weburl : "http://www.recontact.me"},
	  {latLng: [-19.06, -65.76], name: 'Potosi', weburl : "http://www.recontact.me"},
	  {latLng: [-16.35, -68.47], name: 'La Paz', weburl : "http://www.recontact.me"},
	  {latLng: [-15.62, -67.65], name: 'Death road', weburl : "http://www.recontact.me"},
	  {latLng: [-13.72, -71.69], name: 'Cusco', weburl : "http://www.recontact.me"},
	  {latLng: [-13.20, -72.74], name: 'Machu Pichu', weburl : "http://www.recontact.me"},
	  {latLng: [-14.60, -75.14], name: 'Nazca Lines', weburl : "http://www.recontact.me"},
	  {latLng: [-11.65, -77.38], name: 'Lima', weburl : "http://www.recontact.me"},
	  {latLng: [-33.48, -70.87], name: 'Santiago de Chile', weburl : "http://www.recontact.me"},
	  {latLng: [-36.87, 174.74], name: 'Auckland', weburl : "http://www.recontact.me"},
	  {latLng: [-43.71, 170.84], name: 'Tekapo Lake', weburl : "http://www.recontact.me"},
	  {latLng: [-43.09, 170.84], name: 'Mount Cook', weburl : "http://www.recontact.me"},
	  {latLng: [-45.05, 168.67], name: 'Queenstown', weburl : "http://www.recontact.me"},
	  {latLng: [-46.26, 167.92], name: 'Milford Sound', weburl : "http://www.recontact.me"},
	  {latLng: [-44.08, 169.35], name: 'Haast Pass', weburl : "http://www.recontact.me"},
	  {latLng: [-34.35, 150.75], name: 'Sidney', weburl : "http://www.recontact.me"},
	  {latLng: [-34.01, 146.55], name: 'Blue Montains', weburl : "http://www.recontact.me"},
	  {latLng: [-37.69, 145.13], name: 'Melbourne', weburl : "http://www.recontact.me"},
	  {latLng: [-27.13, 152.84], name: 'Brisbane', weburl : "http://www.recontact.me"},
	  {latLng: [-18.03, 148.03], name: 'Great Barrier Reef', weburl : "http://www.recontact.me"},
	  {latLng: [1.49, 103.43], name: 'Singapore', weburl : "http://www.recontact.me"},
	  {latLng: [-8.39, 115.35], name: 'Bali', weburl : "http://www.recontact.me"},
	  {latLng: [-8.61, 116.92], name: 'Gili Islands', weburl : "http://www.recontact.me"},
	  {latLng: [-7.34, 110.11], name: 'Borobudur', weburl : "http://www.recontact.me"},
	  {latLng: [-7.87, 112.80], name: 'Mount Bromo', weburl : "http://www.recontact.me"},
	  {latLng: [13.82, 100.67], name: 'Bankok', weburl : "http://www.recontact.me"},
	  {latLng: [13.31, 104.56], name: 'Angkor', weburl : "http://www.recontact.me"},
	  {latLng: [11.39, 104.49], name: 'Phnom-Penh', weburl : "http://www.recontact.me"},
	  {latLng: [10.50, 106.66], name: 'Hô Chi Minh', weburl : "http://www.recontact.me"},
	  {latLng: [21.16, 105.46], name: 'Hà Noi', weburl : "http://www.recontact.me"},
	  {latLng: [20.51, 106.89], name: 'Halong Bay', weburl : "http://www.recontact.me"},
	  {latLng: [29.65, 103.97], name: 'Sichuan', weburl : "http://www.recontact.me"},
	  {latLng: [34.90, 104.19], name: 'Jiuzhaigou valley', weburl : "http://www.recontact.me"},
	  {latLng: [26.11, 108.61], name: 'Guilin', weburl : "http://www.recontact.me"},
	  {latLng: [39.77, 116.10], name: 'Beijing', weburl : "http://www.recontact.me"},
	  {latLng: [40.97, 116.77], name: 'Great Wall of China', weburl : "http://www.recontact.me"},
	  {latLng: [39.96, 99.62], name: 'Zhangye', weburl : "http://www.recontact.me"},
	  {latLng: [30.67, 90.26], name: 'Lhassa', weburl : "http://www.recontact.me"},
	  {latLng: [30.47, 91.01], name: 'Potala Palace', weburl : "http://www.recontact.me"},
	  {latLng: [27.99, 86.74], name: 'Mount Everest', weburl : "http://www.recontact.me"},
	  {latLng: [27.79, 85.02], name: 'Kahtmandu', weburl : "http://www.recontact.me"},
	  {latLng: [25.06, 83.82], name: 'Varanasi', weburl : "http://www.recontact.me"},
	  {latLng: [22.44, 87.27], name: 'Calcutta', weburl : "http://www.recontact.me"},
	  {latLng: [25.65, 78.43], name: 'Taj Mahal - Agra', weburl : "http://www.recontact.me"},
	  {latLng: [28.75, 77.83], name: 'New Delhi', weburl : "http://www.recontact.me"},
	  {latLng: [23.86, 76.63], name: 'Rajasthan', weburl : "http://www.recontact.me"},
	  {latLng: [33.24, 76.71], name: 'Leh Ladakh', weburl : "http://www.recontact.me"}
];