<?php $urlDropbox = array(
'1' => ['updated'=>TRUE,'img' => ['0' => 'https://dl.dropboxusercontent.com/1/view/4j1qtoviu3epwz3/Chargements%20appareil%20photo/ArticleTdm/1/img0.jpg','1' => 'https://dl.dropboxusercontent.com/1/view/xamcfafmzou562u/Chargements%20appareil%20photo/ArticleTdm/1/img1.jpg','3' => 'https://dl.dropboxusercontent.com/1/view/055o4937dcvnyfm/Chargements%20appareil%20photo/ArticleTdm/1/img3.jpg','2' => 'https://dl.dropboxusercontent.com/1/view/my6eqmf1e53b7qw/Chargements%20appareil%20photo/ArticleTdm/1/img2.jpg'],'gal' => ['0' => 'https://dl.dropboxusercontent.com/1/view/bgxilom2prn5tvm/Chargements%20appareil%20photo/ArticleTdm/1/ghost.jpg','1' => 'https://dl.dropboxusercontent.com/1/view/fjl08l1l39rylpx/Chargements%20appareil%20photo/ArticleTdm/1/cusco.jpg','2' => 'https://dl.dropboxusercontent.com/1/view/4y4wke1ib013z5t/Chargements%20appareil%20photo/ArticleTdm/1/china.jpg','3' => 'https://dl.dropboxusercontent.com/1/view/b9fvj6m83935bcx/Chargements%20appareil%20photo/ArticleTdm/1/cook.jpg','4' => 'https://dl.dropboxusercontent.com/1/view/xie91i7smtynokh/Chargements%20appareil%20photo/ArticleTdm/1/collect.jpg','5' => 'https://dl.dropboxusercontent.com/1/view/z6glvwldqr1l0hm/Chargements%20appareil%20photo/ArticleTdm/1/delhi.jpg','6' => 'https://dl.dropboxusercontent.com/1/view/znt5memkbjykcqy/Chargements%20appareil%20photo/ArticleTdm/1/dubai.jpg','7' => 'https://dl.dropboxusercontent.com/1/view/oudt473llrzbmjy/Chargements%20appareil%20photo/ArticleTdm/1/cambodia.jpg','8' => 'https://dl.dropboxusercontent.com/1/view/zk3iy8opfq94p1z/Chargements%20appareil%20photo/ArticleTdm/1/bromo.jpg','9' => 'https://dl.dropboxusercontent.com/1/view/wcs8ewp86rdyfqz/Chargements%20appareil%20photo/ArticleTdm/1/chile.jpg',]],
'2' => ['updated'=>TRUE,'img' => ['2' => 'https://dl.dropboxusercontent.com/1/view/7nvpt58wdslmpev/chargements%20appareil%20photo/articletdm/2/img2.jpg','1' => 'https://dl.dropboxusercontent.com/1/view/kzgp5j7wl3dttn5/chargements%20appareil%20photo/articletdm/2/img1.jpg','0' => 'https://dl.dropboxusercontent.com/1/view/9czhdkctda1jhng/chargements%20appareil%20photo/articletdm/2/img0.jpg','4' => 'https://dl.dropboxusercontent.com/1/view/qmpasnkxuwdeypf/chargements%20appareil%20photo/articletdm/2/img4.jpg'],'gal' => ['0' => 'https://dl.dropboxusercontent.com/1/view/ja3twejsyeartai/chargements%20appareil%20photo/articletdm/2/china.jpg','1' => 'https://dl.dropboxusercontent.com/1/view/gapd9kg6x427m8w/chargements%20appareil%20photo/articletdm/2/dubai.jpg',]],
'3' => ['updated'=>TRUE,'img' => ['0' => 'https://dl.dropboxusercontent.com/1/view/tmvg8fcirtspcgo/chargements%20appareil%20photo/articletdm/3/img0.jpg','1' => 'https://dl.dropboxusercontent.com/1/view/d1gvvq15qalhdzl/chargements%20appareil%20photo/articletdm/3/img1.jpg','3' => 'https://dl.dropboxusercontent.com/1/view/hghmp9ag9j9kf37/chargements%20appareil%20photo/articletdm/3/img3.jpg','2' => 'https://dl.dropboxusercontent.com/1/view/8axny3h43f77ez4/chargements%20appareil%20photo/articletdm/3/img2.jpg'],'gal' => ['0' => 'https://dl.dropboxusercontent.com/1/view/7bhyxnik3n6xvlt/chargements%20appareil%20photo/articletdm/3/delhi.jpg','1' => 'https://dl.dropboxusercontent.com/1/view/siqx7qitg3jmyxn/chargements%20appareil%20photo/articletdm/3/cusco.jpg',]],
'4' => ['updated'=>TRUE,'img' => ['2' => 'https://dl.dropboxusercontent.com/1/view/10jucm5yxtlk1vq/chargements%20appareil%20photo/articletdm/4/img2.jpg','1' => 'https://dl.dropboxusercontent.com/1/view/egtyefvwxbvucmk/chargements%20appareil%20photo/articletdm/4/img1.jpg','0' => 'https://dl.dropboxusercontent.com/1/view/deuhobmo76llpz0/chargements%20appareil%20photo/articletdm/4/img0.jpg'],'gal' => ['0' => 'https://dl.dropboxusercontent.com/1/view/pv7wd814y6kfvfs/chargements%20appareil%20photo/articletdm/4/delhi.jpg','1' => 'https://dl.dropboxusercontent.com/1/view/9zxeesfheing7dm/chargements%20appareil%20photo/articletdm/4/cusco.jpg',]],
'5' => ['updated'=>TRUE,'img' => ['0' => 'https://dl.dropboxusercontent.com/1/view/39qevcnbga48glt/chargements%20appareil%20photo/articletdm/5/img0.jpg','1' => 'https://dl.dropboxusercontent.com/1/view/e9bbwy2c4uoe3ya/chargements%20appareil%20photo/articletdm/5/img1.jpg','3' => 'https://dl.dropboxusercontent.com/1/view/org7wzgl7igfmnb/chargements%20appareil%20photo/articletdm/5/img3.jpg','2' => 'https://dl.dropboxusercontent.com/1/view/yyqccumpz259q04/chargements%20appareil%20photo/articletdm/5/img2.jpg'],'gal' => ['0' => 'https://dl.dropboxusercontent.com/1/view/wuang5axhq30k6w/chargements%20appareil%20photo/articletdm/5/cusco.jpg','1' => 'https://dl.dropboxusercontent.com/1/view/qmbkckjdtg8ep6f/chargements%20appareil%20photo/articletdm/5/delhi.jpg',]],
'6' => ['updated'=>FALSE,'img' => ['0' => 'https://dl.dropboxusercontent.com/1/view/39qevcnbga48glt/chargements%20appareil%20photo/articletdm/5/img0.jpg','1' => 'https://dl.dropboxusercontent.com/1/view/e9bbwy2c4uoe3ya/chargements%20appareil%20photo/articletdm/5/img1.jpg','3' => 'https://dl.dropboxusercontent.com/1/view/org7wzgl7igfmnb/chargements%20appareil%20photo/articletdm/5/img3.jpg','2' => 'https://dl.dropboxusercontent.com/1/view/yyqccumpz259q04/chargements%20appareil%20photo/articletdm/5/img2.jpg'],'gal' => ['0' => 'https://dl.dropboxusercontent.com/1/view/wuang5axhq30k6w/chargements%20appareil%20photo/articletdm/5/cusco.jpg','1' => 'https://dl.dropboxusercontent.com/1/view/qmbkckjdtg8ep6f/chargements%20appareil%20photo/articletdm/5/delhi.jpg',]],
'7' => ['updated'=>FALSE,'img' => ['0' => 'https://dl.dropboxusercontent.com/1/view/39qevcnbga48glt/chargements%20appareil%20photo/articletdm/5/img0.jpg','1' => 'https://dl.dropboxusercontent.com/1/view/e9bbwy2c4uoe3ya/chargements%20appareil%20photo/articletdm/5/img1.jpg','3' => 'https://dl.dropboxusercontent.com/1/view/org7wzgl7igfmnb/chargements%20appareil%20photo/articletdm/5/img3.jpg','2' => 'https://dl.dropboxusercontent.com/1/view/yyqccumpz259q04/chargements%20appareil%20photo/articletdm/5/img2.jpg'],'gal' => ['0' => 'https://dl.dropboxusercontent.com/1/view/wuang5axhq30k6w/chargements%20appareil%20photo/articletdm/5/cusco.jpg','1' => 'https://dl.dropboxusercontent.com/1/view/qmbkckjdtg8ep6f/chargements%20appareil%20photo/articletdm/5/delhi.jpg',]],
'8' => ['updated'=>FALSE,'img' => ['0' => 'https://dl.dropboxusercontent.com/1/view/39qevcnbga48glt/chargements%20appareil%20photo/articletdm/5/img0.jpg','1' => 'https://dl.dropboxusercontent.com/1/view/e9bbwy2c4uoe3ya/chargements%20appareil%20photo/articletdm/5/img1.jpg','3' => 'https://dl.dropboxusercontent.com/1/view/org7wzgl7igfmnb/chargements%20appareil%20photo/articletdm/5/img3.jpg','2' => 'https://dl.dropboxusercontent.com/1/view/yyqccumpz259q04/chargements%20appareil%20photo/articletdm/5/img2.jpg'],'gal' => ['0' => 'https://dl.dropboxusercontent.com/1/view/wuang5axhq30k6w/chargements%20appareil%20photo/articletdm/5/cusco.jpg','1' => 'https://dl.dropboxusercontent.com/1/view/qmbkckjdtg8ep6f/chargements%20appareil%20photo/articletdm/5/delhi.jpg',]],
'9' => ['updated'=>FALSE,'img' => ['0' => 'https://dl.dropboxusercontent.com/1/view/39qevcnbga48glt/chargements%20appareil%20photo/articletdm/5/img0.jpg','1' => 'https://dl.dropboxusercontent.com/1/view/e9bbwy2c4uoe3ya/chargements%20appareil%20photo/articletdm/5/img1.jpg','3' => 'https://dl.dropboxusercontent.com/1/view/org7wzgl7igfmnb/chargements%20appareil%20photo/articletdm/5/img3.jpg','2' => 'https://dl.dropboxusercontent.com/1/view/yyqccumpz259q04/chargements%20appareil%20photo/articletdm/5/img2.jpg'],'gal' => ['0' => 'https://dl.dropboxusercontent.com/1/view/wuang5axhq30k6w/chargements%20appareil%20photo/articletdm/5/cusco.jpg','1' => 'https://dl.dropboxusercontent.com/1/view/qmbkckjdtg8ep6f/chargements%20appareil%20photo/articletdm/5/delhi.jpg',]],
'10' => ['updated'=>TRUE,'img' => ['3' => 'https://dl.dropboxusercontent.com/1/view/u8i3gfp6dgvk9l9/chargements%20appareil%20photo/articletdm/10/img3.jpg','2' => 'https://dl.dropboxusercontent.com/1/view/u7dqfdzbmcd77h7/chargements%20appareil%20photo/articletdm/10/img2.jpg','0' => 'https://dl.dropboxusercontent.com/1/view/t7tpmlf26qn9yuf/chargements%20appareil%20photo/articletdm/10/img0.jpg','1' => 'https://dl.dropboxusercontent.com/1/view/04o8fzh7s9k1267/chargements%20appareil%20photo/articletdm/10/img1.jpg'],'gal' => ['0' => 'https://dl.dropboxusercontent.com/1/view/az47reyezkm609n/chargements%20appareil%20photo/articletdm/10/blabla.jpg',]],
'11' => ['updated'=>FALSE,'img' => ['0' => 'https://dl.dropboxusercontent.com/1/view/39qevcnbga48glt/chargements%20appareil%20photo/articletdm/5/img0.jpg','1' => 'https://dl.dropboxusercontent.com/1/view/e9bbwy2c4uoe3ya/chargements%20appareil%20photo/articletdm/5/img1.jpg','3' => 'https://dl.dropboxusercontent.com/1/view/org7wzgl7igfmnb/chargements%20appareil%20photo/articletdm/5/img3.jpg','2' => 'https://dl.dropboxusercontent.com/1/view/yyqccumpz259q04/chargements%20appareil%20photo/articletdm/5/img2.jpg'],'gal' => ['0' => 'https://dl.dropboxusercontent.com/1/view/wuang5axhq30k6w/chargements%20appareil%20photo/articletdm/5/cusco.jpg','1' => 'https://dl.dropboxusercontent.com/1/view/qmbkckjdtg8ep6f/chargements%20appareil%20photo/articletdm/5/delhi.jpg',]],
































































































);?>



































